name: Build and Deploy
on:
  push:
    branches:
      - main

permissions:
  contents: write
  packages: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: |
          cat <<EOF > build.sh
          #!/bin/sh
          set -e

          echo "::group::Check Formatting and Linting"
          pnpm run lint
          pnpm run format
          git diff --exit-code
          echo "::endgroup::"

          echo "::group::Generate Icons"
          pnpm run generate-icons
          echo "::endgroup::"

          echo "::group::Build"
          pnpm run build
          echo "::endgroup::"
          EOF

      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/dhhyi/gin-rummy-scoreboard-devcontainer-cache
          cacheFrom: ghcr.io/dhhyi/gin-rummy-scoreboard-devcontainer-cache
          push: always
          runCmd: sh build.sh

      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          branch: gh-pages
          clean: false
